# fly.toml app configuration file generated for portifolio-little-haze-9451 on 2025-03-21T16:37:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portifolio-little-haze-9451'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
